### ISSUE TITLE
Add name of node to test_check_module_versions and test_check_services

### ISSUE THREAD

**Issue by dkulykovmirantis** [msenin94/mk-post-deployment-checks#94]
Add name of node to test_check_module_versions
The same for test_check_services

It was implemented in test_check_package

**Comment by legan4ik** [comment]
https://github.com/msenin94/mk-post-deployment-checks/pull/95

**Comment by legan4ik** [comment]
Is it done?

**Comment by dkulykovmirantis** [comment]
yeap 
Closed
